# Generated by Django 5.1.15 on 2026-04-28 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('type', models.CharField(choices=[('news', '뉴스'), ('video', '동영상'), ('search_trend', '검색 트렌드'), ('sns', 'SNS')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', '성공'), ('partial', '부분 성공'), ('failed', '실패'), ('running', '실행 중')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('items_collected', models.IntegerField(default=0)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='content.source')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('llm_summary', models.TextField(blank=True, null=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='items', to='industries.industry')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.source')),
            ],
            options={
                'ordering': ('-published_at', '-collected_at'),
                'indexes': [models.Index(fields=['published_at'], name='content_con_publish_5be4f6_idx'), models.Index(fields=['collected_at'], name='content_con_collect_4eb099_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='TrendKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120)),
                ('rank', models.IntegerField()),
                ('observed_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('industries', models.ManyToManyField(blank=True, related_name='trends', to='industries.industry')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='content.source')),
            ],
            options={
                'ordering': ('rank',),
                'indexes': [models.Index(fields=['observed_at', 'source'], name='content_tre_observe_c45889_idx')],
            },
        ),
    ]
