# Generated by Django 5.1.15 on 2026-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='표시용. 비우면 채널 메타에서 가져옴.', max_length=120)),
                ('handle', models.CharField(help_text='@핸들 (예: @sebasi15) 또는 channel ID (예: UCxxxxxx).', max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_active', 'name', 'id'),
            },
        ),
    ]
